### ISSUE TITLE
Report bug

### ISSUE THREAD

**Issue by dvFelipe** [0dayYakuza/RuskiPlugin#1]
Hello, I was using this plugin to sell ores, but I encountered a possible bug. The functions: "Sell by PET Trade CPU" and "Sell ores by Trade Drone HMD_07" are working fine, but the function: "Sell ores on base" has a bug that prevents the sale of ores.

**Bug Details**

When selecting the option: "Sell ores on base," the ship travels to the selected map (x8 or x1). Upon reaching the base and interacting with the sales module, the ship moves before the sales screen even opens. Clicking the buttons to sell the ores simply doesn't work. The button selection animation appears, but the sale doesn't happen.

**What this causes:**
The ship keeps moving in and out of the base, trying to make the sale but failing, preventing it from returning to kill NPCs on the map it was previously on.

Possible solution:
Ensure the ship does not move after clicking on the sales module at the base. If possible, increase the wait time between selling each ore. Check if all ores have been sold before returning to the previous map.

Note: I am not familiar with the programming language used, and I had a lot of difficulty trying to solve the problem in the code, which is why I decided to open a "report."

**Comment by 0dayYakuza** [comment]
I'm not maintaining my plugin anymore. Check #coding channel in darkbot discord.
The only solution is if someone random dude will fix it (or you, ask chatgpt for help).
